---
- hosts: all
  roles:
    - helloWorld
    - common

- hosts: tag_purpose_awx_monitor
  roles:
    - containers
    - prometheus
  vars:
    - container_engine: docker

#- hosts: tag_purpose_awx_bastion
#  roles:

