---
- hosts: all
  roles:
    - common

- hosts: tag_purpose_awx_monitor
  roles:
    - containers
    - prometheus
  vars:
    - container_engine: docker

- hosts: tag_purpose_awx_etcd
  roles:
    - containers
    - etcd
  vars:
    - container_engine: docker
