---
- name: Get Distro Name
  debug:
    msg: "{{ ansible_distribution }}"

- name: Update disto packages
  yum:
    name: '*'
    state: latest
  when:
    - ansible_distribution == 'RedHat'
  tags:
    - patch
