---
- name: Get Distro Name
  debug:
    msg: "{{ ansible_distribution }}"

- name: Yum update
  yum:
    name: '*'
    state: latest
  register: patching
  when:
    - ansible_distribution == 'RedHat'
  tags:
    - patch

- name: Apt upgrade
  apt:
    name: '*'
    state: latest
  register: patching
  when:
    - ansible_distribution == 'Debian'
  tags:
    - patch

- name: Get Distro Name
  debug:
    msg: "Patching: {{ patching }}"

- name: Fail if package_update isn't successful
  fail:
    msg: "Host Patching Failed!"
  when:
    - patching is not succeeded
