---
- name: Enable rhel server extras
  ini_file:
    path: /etc/yum.repos.d/redhat-rhui.repo
    section: rhui-REGION-rhel-server-extras
    option: enabled
    value: 1
  tags:
    - repos
    - containers

- name: install Docker-Py
  package:
    name: python-docker-py
  when:
    - container_engine == 'docker'

- name: install container engine
  package:
    name: "{{ container_engine }}"
    state: present
  tags:
    - packages
    - containers
