---
- name: Enable rhel server extras
  ini_file:
    path: /etc/yum.repos.d/redhat-rhui.repo
    section: rhui-REGION-rhel-server-extras
    option: enabled
    value: 1
  tags:
    - repos
    - containers

- name: Enable rhel server scl
  ini_file:
    path: /etc/yum.repos.d/redhat-rhui.repo
    section: rhui-REGION-rhel-server-rhscl
    option: enabled
    value: 1
  tags:
    - repos
    - containers

- name: install pip
  package:
    state: present
    name: python27-python-pip
  when:
    - container_engine == 'docker'

- name: install Docker-Py
  pip:
    name: docker-py
  when:
    - container_engine == 'docker'

- name: install container engine
  package:
    name: "{{ container_engine }}"
    state: present
  tags:
    - packages
    - containers
