---
- name: Ensure dbus is installed to set hostname on Debian  
  apt:
    name: dbus
    state: latest
  when:
    - ansible_distribution == 'Debian'

- name: Set hostname
  hostname:
    name: "{{ ec2_tag_Name }}"

- name: fqdn in prompt
  lineinfile:
    path: /root/.bashrc
    line: 'PS1="[\u@\H \W] \$ "'
